import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { dbConnect } from "@/service/mongo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Skillseed",
  description: "Generated by Skillseed",
  icons: {
    icon: "/assets/logo.png", 
  },
};

export default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
   await dbConnect()
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster richColors position="top-center"/>
      </body>
    </html>
  );
}
